### ISSUE TITLE
Detecting generating file dirs

### ISSUE THREAD

**Issue by EPashkin** [gkoz/gir#99]
In gtk currently we have next dirs for classes: dialog, widgets, window.
For automatic detect dirs propose add path to `object` in gir.toml and select path for nearest parent with path.
```
[[object]]
name = "Gtk.Widget"
path = "widgets"

[[object]]
name = "Gtk.Window"
path = "window" # or "windows"

[[object]]
name = "Gtk.Dialog"
path = "dialog" # "dialogs"
```
This can be expanded to interfaces (but needed list all choosers as its has no common parent).

Maybe it unnecessary or has better solution.

**Comment by gkoz** [comment]
When I started adding some directory structure, I hadn't thought through the automatic generation angle and was hoping to have nested namespace structure.
Since then I've realized that it's better to be consistent with other bindings (e.g. `gtkmm`) and have a flat organization: all modules under `src` and all types reexported in `lib.rs`. This way is also more generator-friendly.

**Comment by gkoz** [comment]
It however may be worth it to put the autogenerated files in a separate module/directory so they would be clearly isolated from the manual ones.

**Comment by EPashkin** [comment]
So just place all generated in `src/auto`?
It can be done later, now all still go to `src/widgets`.

**Comment by gkoz** [comment]
Agreed.
